version: 2
models:
  - name: stg_yellow_union
    columns:
      - name: total_amount
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              config:
                severity: warn               # ← don’t fail the build here
              arguments:
                min_value: -100
                max_value: 1500